### ISSUE TITLE
一开始没有缓存，突然来了n 个相同的方法调用，n 个方法都会在处理一次数据

### ISSUE THREAD

**Issue by Fierygit** [pugwoo/redis-helper#1]
https://github.com/pugwoo/redis-helper/blob/7e78eb7dff7eb22e456dd9d31c60a339b024a3bb/src/main/java/com/pugwoo/wooutils/cache/HiSpeedCacheAspect.java#L151

**Comment by Fierygit** [comment]
<img width="233" alt="image" src="https://user-images.githubusercontent.com/36060301/154655694-17d4c8b7-95a7-4354-8056-00a6aa0da58c.png">
幂等方法可以只掉用一次，大部分方法都应该是幂等的

**Comment by pugwoo** [comment]
这个问题，目前是的，也不好处理让其它n-1个等待

所以统一的简单逻辑是：有缓存用缓存，没缓存则调用

这个缓存本身不处理高并发下只调用一次的问题，所以本质上是两个问题

即便我们可以做到去缓存另外n-1个，也有点两难，万一第一个调用失败了呢

所以，从设计的角度，暂维持现有方式。
