### ISSUE TITLE
当方法有参数时， 而keyscript默认为空， 忘记填写时，此时应该把所有参数值作为key 合理，或者 log 提示

### ISSUE THREAD

**Issue by Fierygit** [pugwoo/redis-helper#2]
https://github.com/pugwoo/redis-helper/blob/7e78eb7dff7eb22e456dd9d31c60a339b024a3bb/src/main/java/com/pugwoo/wooutils/cache/HiSpeedCache.java#L23

**Comment by Fierygit** [comment]
现在默认没有填写 keyscript 时， 会忽略参数值

**Comment by pugwoo** [comment]
不错的建议，log提示比较合理

**Comment by pugwoo** [comment]
Supported since 1.1.7
